using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;
using Xunit.Abstractions;

namespace CodeGenHelpers.Tests
{
    public class CodeBuilderTests : TestBase
    {
        public CodeBuilderTests(ITestOutputHelper testOutput)
            : base(testOutput)
        {
        }

        [Fact]
        public void AddsCustomAutoGeneratedMessage()
        {
            var builder = CodeBuilder.Create(Namespace)
                .WithAutoGeneratedMessage(@"This is a Custom Defined Message
See my Custom Copyright Message

Don't Make Changes to this File!!!");

            MakeAssertion(builder, "CustomAutoGeneratedMessage");
        }
    }
}
