using Xunit;
using Xunit.Abstractions;

namespace CodeGenHelpers.Tests
{
    public class MethodTests
    {
        private readonly ITestOutputHelper _testOutputHelper;

        public MethodTests(ITestOutputHelper testOutputHelper)
        {
            _testOutputHelper = testOutputHelper;
        }

        [Fact]
        public void GenerateAbstractMethod()
        {
            var builder = CodeBuilder.Create("AwesomeApp")
                .AddClass("SampleClass")
                .AddMethod("MyAbstractMethod")
                .Abstract()
                .Class;

            var expected = @"namespace AwesomeApp
{
    partial class SampleClass
    {
        abstract void MyAbstractMethod()
        {
        }
    }
}
";
            _testOutputHelper.WriteLine(expected);
            _testOutputHelper.WriteLine("____________________");
            _testOutputHelper.WriteLine(builder.Build());
            AreEqual(expected, builder);
        }

        private void AreEqual(string expected, ClassBuilder builder)
        {
            var expectedOutput = $@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

{expected}";

            Assert.Equal(expectedOutput, builder.Build(), ignoreLineEndingDifferences: true, ignoreWhiteSpaceDifferences: true);
        }
    }
}
