//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenHelpers.SampleCode
{
    partial class CanPassMultipleParametersOfSameType
    {
         CanPassMultipleParametersOfSameType(string str1, string str2)
            : base(str1, str2)
        {
        }
    }
}
