//------------------------------------------------------------------------------
// <auto-generated>
//     This is a Custom Defined Message
//     See my Custom Copyright Message
//
//     Don't Make Changes to this File!!!
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenHelpers.SampleCode
{
}
