//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace CodeGenHelpers.SampleCode
{
    public enum SampleEnum3
    {
        [Description("Hello World")]
        Foo,

        [Description("Bar")]
        Bar
    }
}
