//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CodeGenHelpers.SampleCode
{
    partial class SamplePrimitiveParameter
    {
        public void MyPrimitiveMethod(string myParameter)
        {
            Console.WriteLine("Hello {0}", myParameter);
        }
    }
}
