//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenHelpers.SampleCode
{
    public record SampleRecordInitProperty
    {
        public string FirstName { get; init; }
        public string LastName { get; init; }
        public int Age { get; init; } = 1;
    }
}
