//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CodeGenHelpers.SampleCode
{
    partial class SampleClassWithPropertiesNotSorted
    {
        public string PropZ;

        public string PropC;

        public string PropB;

        public string PropA;

        public string PropD;
    }
}
