name: Build CodeGenHelpers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build CodeGenHelpers
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Setup .NET Core 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: NuGet Restore
        run: dotnet restore

      - name: Build Packages
        run: dotnet build .\CodeGenHelpers.sln -c Release

      - name: Test
        run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build -c Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NuGet
          path: Artifacts/

      - name: NuGet Publish (In-House)
        if: ${{ github.event_name != 'pull_request' }}
        uses: dansiegel/publish-nuget@v1.01
        with:
            filename: 'Artifacts/*.nupkg'
            feedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
            apiKey: ${{ secrets.IN_HOUSE_API_KEY }}
